wip
- Use zstyle instead of env vars for configuration and state;
- Use nested functions to avoid polluting the shell environment;
- Replace tell-terminal/tell-iterm with custom .applescript files and
  use osascript directly;
- Merge support for current and upcoming iTerm and for tmux;

diff --git a/notify-if-background b/notify-if-background
--- a/notify-if-background
+++ b/notify-if-background
@@ -1,87 +1,223 @@
 # vim: set nowrap filetype=zsh:
+# 
+# Post a desktop notification if the terminal application is detected to be in
+# background (eg.: the current shell window is not the active one in the
+# application, or if the application itself is not frontmost).
 #
-# Post a notification using either Notification Center using
-# terminal-notifier.app or Growl, through growlnotify.
+# By default, notification is posted to Notification Center through
+# terminal-notifier on a Mac, or using notify-send on Linux.
 #
-# Notification is effectively posted only if the terminal application
-# (either Terminal.app or iTerm2) is in background, or if the session tab
-# is not active (or in other word when you are not looking at the shell). 
+# The default notifier function can be replaced with a custom
+# program/script/function using zstyle:
 #
-# Exits with status 1 if the terminal app is unsupported, or if the
-# notifier program is not found.
+#     zstyle -s ':notify:*' notifier ~/bin/my-notifier
 #
-# Exits with status 2 if the terminal is frontmost or the tab is active.
+# Anything that can be piped a message on standard input and the notification
+# type (either "error" or "success") as it's first argument can be used as the
+# notifier.
 #
-# Requirements:
+# If you want to bring the terminal application to front after the notification
+# is posted use:
 #
-# - terminal-notifier.app
-#   https://github.com/alloy/terminal-notifier 
+#    zstyle ':notify:*' activate-terminal yes
 #
-# - growlnotify
-#   http://growl.info/extras.php/#growlnotify
+# notify-if-background will exit with status 1 if the terminal application is
+# not one for which we know how to query the "frontmost/background" status, and
+# with status 2 if the terminal application or the current shell tab/window is
+# active.
+() {
+    local term_id type message notifier
 
-local term_id title icon_switch the_tty
-local -a otitle oicon
-zparseopts t:=otitle -icon:=oicon
+    type=$1
+    message=$(<&0)
 
-icon=$oicon[2]
-title=$otitle[2]
-message=$(<&0)
+    # Find a "term_id", a string that will be used later to dispatch different
+    # commands to determine whether the terminal application is active or in
+    # background.
+    function find-current-term-id {
+        local resources_dir
+        zstyle -s ':notify:' resources-dir resources_dir
 
-[[ -z "$SYS_NOTIFIER" ]] \
-  && SYS_NOTIFIER="/usr/local/bin/terminal-notifier"
+        if [[ "$TERM_PROGRAM" == 'iTerm.app' ]]; then
+            # Try to detect recent iTerm2 builds that use the different AS
+            # dictionary by running a script that will fail in newer but
+            # succeed in older versions.
+            if osascript "$resources_dir"/fails-on-iterm-nightly.applescript 2>/dev/null; then
+                echo iterm2
+            else
+                echo iterm2-nightly
+            fi
+        elif [[ "$TERM_PROGRAM" == 'Apple_Terminal' ]]; then
+            echo apple-terminal
+        elif which xdotool > /dev/null 2>&1; then
+            echo xdotool
+        else
+            return 1
+        fi
+    }
 
-[[ -z "$GROWL_NOTIFIER" ]] \
-  && GROWL_NOTIFIER="/usr/local/bin/growlnotify"
+    # Exit with 0 if inside a TMUX pane
+    function is-inside-tmux {
+        if [[ -z "$TMUX" ]]; then
+            return 1
+        else
+            return 0
+        fi
+    }
 
-if [[ "$TERM_PROGRAM" == 'iTerm.app' ]]; then
-  term_id='com.googlecode.iterm2'
-elif [[ "$TERM_PROGRAM" == 'Apple_Terminal' ]]; then
-  term_id='com.apple.terminal'
-else
-  # echo "Unsupported terminal: $TERM_PROGRAM" > /dev/stderr 
-  return 1;
-fi
+    # Find the TTY for the current shell.
+    function find-current-tty {
+        if is-inside-tmux; then
+          tmux display-message -p '#{client_tty}'
+        else
+          echo $TTY
+        fi
+    }
 
-if [[ -n ${TMUX+1} ]]; then
-  the_tty=`tmux display-message -p '#{client_tty}'`
-else
-  the_tty=$TTY
-fi
+    # Get the active TMUX pane ID, comparable with $TMUX_PANE
+    function find-tmux-pane {
+        if is-inside-tmux; then
+            tmux list-windows -F '#{window_active} #{pane_id}' | grep -i '^1' | awk '{ print $2 }'
+        else
+            return 1
+        fi
+    }
 
-if [[ $term_id == 'com.googlecode.iterm2' ]]; then
-  # Use System Events as there's no frontmost property at least in current nightly
-  local iterm_frontmost tty_active
-  iterm_frontmost=`osascript <<OSA
-        tell application "System Events"
-            tell item 1 of (application processes whose bundle identifier is "com.googlecode.iterm2") to ¬
-                get its frontmost
-        end tell
-OSA`
+    # Exit with 0 if given TMUX pane is the active one.
+    function is-tmux-pane-active {
+        local pane
+        pane=$1
 
-  tty_active=`tell-iterm2 <<< "tty of (current session of current tab of current window) is equal to \"$the_tty\""`
+        if [[ "$TMUX_PANE" == "$pane" ]]; then
+            return 0
+        fi
 
-  if [[ $iterm_frontmost == "true" && $tty_active == "true" ]]; then
-    return 2
-  fi
-else
-  TT='tell-terminal'
-  if [[ `$TT <<<frontmost` == "true" && `$TT -tab <<<selected` == "true" ]]; then
-    return 2
-  fi
-fi
+        return 1
+    }
 
-#cat /dev/stdin | growlnotify "$@"
-# growlnotify "$@" < /dev/stdin
+    # Exit with 0 if the terminal window/tab is active; exit with 1 if not, or
+    # if the terminal is
+    function is-terminal-window-active {
+        local term_id
+
+        term_id=$1
+
+        case "$term_id" in
+            "iterm2"|"iterm2-nightly"|"apple-terminal")
+                local current_tty resources_dir
+
+                zstyle -s ':notify:' resources-dir resources_dir
+                current_tty=$(find-current-tty)
+
+                if [[ "true" == $(osascript "$resources_dir"/is-"$term_id"-active.applescript "$current_tty") ]]; then
+                    return 0
+                fi
+            ;;
+            "xdotool")
+                local active_wid
+
+                active_wid=$(xdotool getactivewindow)
+
+                if [[ "$active_wid" == "$WINDOWID" ]]; then
+                    return 0
+                fi
+            ;;
+        esac
+        return 1
+    }
+
+    # Detect if the terminal application is in background, also accounting
+    # for TMUX if needed, exiting with status 1 if it's active.
+    function is-in-background {
+        local term_id
+
+        term_id=$1
+
+        if is-terminal-window-active "$term_id"; then
+            if is-inside-tmux; then
+                local tmux_pane
+
+                tmux_pane=$(find-tmux-pane)
+
+                if is-tmux-pane-active "$tmux_pane"; then
+                    return 1
+                else
+                    return 0
+                fi
+            fi
+            return 1
+        fi
+
+        return 0
+    }
+
+    function notifier {
+        local notification_title message type
+        local -A titles
+
+        titles=(error "#fail" success "#win")
+        type=$1
+        message=$(<&0)
+
+        zstyle -s ':notify:' "$type"-notification-title notification_title \
+            || notification_title="$titles[$type]"
+
+        function notifier-mac {
+            local app_id app_id_option
+
+            if [[ "$TERM_PROGRAM" == 'iTerm.app' ]]; then
+                app_id="com.googlecode.iterm2"
+            elif [[ "$TERM_PROGRAM" == 'Apple_Terminal' ]]; then
+                app_id="com.apple.terminal"
+            fi
+
+            if [[ ! -z "$app_id" ]]; then
+                app_id_option="-activate $app_id -sender $app_id"
+            fi
+
+            eval "terminal-notifier $app_id_option -appIcon \"$icon\" -title \"$notification_title\" -message \"$message\" 1>/dev/null"
+
+            if zstyle -t ':notify:' activate-terminal; then
+                echo tell app id \"$app_id\" to activate | osascript 1>/dev/null
+            fi
+        }
+
+        function notifier-linux {
+            notify-send "$notification_title" "$message"
+
+            if which wmctrl > /dev/null 2>&1; then
+                local parent_pid
+
+                zstyle -s ':notify:' parent-pid parent_pid
+
+                if zstyle -t ':notify:' activate-terminal; then
+                    wmctrl -ia $(wmctrl -lp | awk -vpid=$parent_pid '$3==pid {print $1; exit}')
+                else
+                    wmctrl -i -r $(wmctrl -lp | awk -vpid=$parent_pid '$3==pid {print $1; exit}') -b add,demands_attention
+                fi
+            fi
+        }
+
+        if which terminal-notifier > /dev/null 2>&1; then
+            notifier-mac
+        elif which notify-send > /dev/null 2>&1; then
+            notifier-linux
+        else
+            echo "No notifier program found." >&2
+            return 1
+        fi
+    }
 
 
-if [[ -x "$SYS_NOTIFIER" ]]; then
-  "$SYS_NOTIFIER" -activate "$term_id" -sender "$term_id" -title "$title" -message "$message" 1>/dev/null 
-elif [[ -x "$GROWL_NOTIFIER" ]]; then
-  [[ ! -z "$icon" ]] && icon_switch="--iconpath $icon"
-  echo "$message" | "$GROWL_NOTIFIER" "$title"
-else
-  echo "No notifier program found." > /dev/stderr
-  return 1
-fi
+    term_id=$(find-current-term-id) \
+        || return 1
+
+    is-in-background "$term_id" \
+        || return 2
+
+    zstyle -s ':notify:' notifier notifier \
+        || notifier=notifier
+
+    echo "$message" | "$notifier" "$type"
+} "$1"
 
